### ISSUE TITLE
Drag and drop exercises and images on the realtime preview

### ISSUE THREAD

**Issue by almerion** [DUT-Info-Montreuil/SAE-Generateur-Dexo#26]
As a user I want to be able to drag and drop exercises and images in order to intuitively create my exercises

- [x] Images is draggable
- [x] Exercises is draggable

**Comment by almerion** [comment]
As a user I want to be able to drag and drop exercises and images in order to intuitively create my exercices

**Comment by NaulaN** [comment]
Maybe one solution here -> https://developer.mozilla.org/fr/docs/Web/API/HTML_Drag_and_Drop_API
