### ISSUE TITLE
Upload of images

### ISSUE THREAD

**Issue by almerion** [DUT-Info-Montreuil/SAE-Generateur-Dexo#4]
As a user i want to be able to use personal images in order to use them on my exercise pages

- [ ] Compressing images
- [ ] Upload vie url
- [x] Upload from computer
- [ ] Limit of size per image

**Comment by NaulaN** [comment]
The uploading function must be optimal

We'll must try compressing the image before save the picture into the server (for exemple `jpeg` format) 
Have a limit of `Mo` per image

**Comment by NaulaN** [comment]
Also, a size limit for not overload the server

**Comment by NaulaN** [comment]
> The uploading function must be optimal
> 
> We'll must try compressing the image before save the picture into the server (for exemple `jpeg` format) Have a limit of `Mo` per image

@MehediT look this https://github.com/fengyuanchen/compressorjs
